demo/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from .views import HomePageView, FormHorizontalView, FormInlineView, PaginationView, FormWithFilesView, \
    DefaultFormView, MiscView, DefaultFormsetView, DefaultFormByFieldView, AngularView

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^formset$', DefaultFormsetView.as_view(), name='formset_default'),
    url(r'^form$', DefaultFormView.as_view(), name='form_default'),
    url(r'^form_by_field$', DefaultFormByFieldView.as_view(), name='form_by_field'),
    url(r'^form_horizontal$', FormHorizontalView.as_view(), name='form_horizontal'),
    url(r'^form_inline$', FormInlineView.as_view(), name='form_inline'),
    url(r'^form_with_files$', FormWithFilesView.as_view(), name='form_with_files'),
    url(r'^pagination$', PaginationView.as_view(), name='pagination'),
    url(r'^misc$', MiscView.as_view(), name='misc'),
    url(r'^angular$', AngularView.as_view(), name='angular'),
]

dq/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url
from . import views
############################## bootstrap 3 ##############################
######################################################################################

app_name ='dq'
urlpatterns = [
    url(r'^dummy', views.dummy, name='dummy'),    
    url(r'^base', views.base, name='base'),

    url(r'^$', views.base, name='base'),     
    #vrfy
    url(r'^vrfys', views.vrfy_list, name='vrfy_list'),
    url(r'^vrfy/create$', views.vrfy_create, name='vrfy_new'),
    url(r'^vrfy/update/(?P<pk>\d+)', views.vrfy_update, name='vrfy_edit'),
    url(r'^vrfy/delete/(?P<pk>\d+)', views.vrfy_delete, name='vrfy_delete'),
    # 오로가 검증대상을 일괄로 수행해줌   
    # curl -d env=dev http://localhost:8001/dq/vrfy/tasks_aurora/
    url(r'^vrfy/tasks_aurora/', views.vrfy_tasks_aurora, name='vrfy_tasks_aurora'),  

    url(r'^vrfy/tasks/', views.vrfy_tasks, name='vrfy_tasks'),    
    url(r'^vrfy/job/(?P<pk>\d+)', views.vrfy_job, name='vrfy_job'),
    url(r'^vrfy/run/(?P<pk>\d+)', views.vrfy_run, name='vrfy_run'),
    #vrfyLog 
    url(r'^vrfyLog_ajax/', views.vrfyLog_ajax, name='vrfyLog_ajax'),     
    url(r'^vrfyLog_ajax_view/', views.vrfyLog_ajax_view, name='vrfyLog_ajax_view'),
    url(r'^vrfyLogs', views.vrfyLog_list, name='vrfyLog_list'),

    #TableCopy
    url(r'^tblCpys2', views.tblCpy_list2, name='tblCpy_list2'),    
    url(r'^tblCpys', views.tblCpy_list, name='tblCpy_list'),
    url(r'^tblCpy_ajax', views.tblCpy_ajax, name='tblCpy_ajax'),
    url(r'^tblCpy/create$', views.tblCpy_create, name='tblCpy_new'),
    url(r'^tblCpy/update/(?P<pk>\d+)', views.tblCpy_update, name='tblCpy_edit'),
    url(r'^tblCpy/delete/(?P<pk>\d+)', views.tblCpy_delete, name='tblCpy_delete'),

    #ilm(information lifecycle mgmt.)
    url(r'^ilms', views.ilm_list, name='ilm_list'),
    url(r'^ilm/create$', views.ilm_create, name='ilm_new'),
    url(r'^ilm/update/(?P<pk>\d+)', views.ilm_update, name='ilm_edit'),
    url(r'^ilm/delete/(?P<pk>\d+)', views.ilm_delete, name='ilm_delete'),
    
    #task
    url(r'^tasks', views.tasks, name='tasks'),
    #vrfyCmd
    url(r'^vrfy_Cmds', views.vrfy_Cmd_list, name='vrfy_Cmd_list'),
    url(r'^vrfy_Cmd/create$', views.vrfy_Cmd_create, name='vrfy_Cmd_new'),
    url(r'^vrfy_Cmd/update/(?P<pk>\d+)', views.vrfy_Cmd_update, name='vrfy_Cmd_edit'),
    url(r'^vrfy_Cmd/delete/(?P<pk>\d+)', views.vrfy_Cmd_delete, name='vrfy_Cmd_delete'),       
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^mdl2tbl/', include('mdl2tbl.urls')),
    url(r'^dq/', include('dq.urls')), 
    #url(r'^erd/', include('erd.urls')),     
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^', include('demo.urls')),    
]

dq/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django import forms
from django.forms.formsets import BaseFormSet, formset_factory
from django.forms import ModelForm
from bootstrap3.tests import TestForm
############################## dbConn  ##############################
from .models import * 

###############################################################################
class VrfyForm(ModelForm):
    class Meta:
        model = Vrfy
        fields = ['DB_NM', 'SCHEMA_NM', 'CLSF_NM1', 'CLSF_NM2'
                 , 'VRFY_TYPE_CD','VRFY_NM','VRFY_EXPLN'
                 ,'TABLE_HANGL_NM','TABLE_NM', 'REFRC_TABLE_HANGL_NM','REFRC_TABLE_NM'
                 ,'USE_YN','CMD_TYPE_CD','CMD_CNTS'
        ,'RGSTR_ID'
        #,'RGST_DTTM'
        ,'MODR_ID'
        #,'MODI_DTTM'
        ]
        widgets = {
            'VRFY_EXPLN' : forms.Textarea(attrs={'rows':2}),
            'CMD_CNTS' : forms.Textarea(attrs={'rows':7}),
        }

###############################################################################
class TableCopyForm(ModelForm):
    class Meta:
        model = TableCopy
        fields = ['TABLE_NM'       
                    ,'TABLE_HANGL_NM'
                    ,'TABLE_COPY_EXPLN'
                    ,'USE_YN'
                    ,'RGSTR_ID'
                    #,'RGST_DTTM'
                    ,'MODR_ID'
                    #,'MODI_DTTM'
                    ]
        widgets = {
            'TABLE_COPY_EXPLN' : forms.Textarea(attrs={'rows':4})
        }

###############################################################################
class IlmForm(ModelForm):
    class Meta:
        model = Ilm
        fields = ['DB_NM', 'SCHEMA_NM', 'CLSF_NM1', 'CLSF_NM2'
                 , 'ILM_TYPE_CD','ILM_NM','ILM_EXPLN'
                 , 'TABLE_HANGL_NM','TABLE_NM','ILM_SEQ'
                 , 'EXPCT_CNT', 'PRESER_PRD_VAL'
                 ,'USE_YN','CMD_TYPE_CD','CMD_CNTS'
        ,'RGSTR_ID'
        #,'RGST_DTTM'
        ,'MODR_ID'
        #,'MODI_DTTM'
        ]
        widgets = {
            'ILM_EXPLN' : forms.Textarea(attrs={'rows':2}),
            'CMD_CNTS' : forms.Textarea(attrs={'rows':7}),
        }

###############################################################################
class vrfy_CmdForm(ModelForm):
    class Meta:
        model = Vrfy_Cmd
        fields = [ 'VRFY_NO','VRFY_SEQ', 'AUTO_CK_YN', 'CMD_DVS_CD', 'CMD_TYPE_CD', 'CMD_CNTS','DTL_VRFY_YN'
        ,'RGSTR_ID'
        #,'RGST_DTTM'
        ,'MODR_ID'
        #,'MODI_DTTM'
        ]      
###############################################################################
class EnvForm(forms.Form):
    ENV_DVS_CD = (
        ('all', '전체환경'),
        ('dev', '개발환경'),
        ('tst', '테스트환경'),
        ('prd', '운영환경'),
    )
    env = forms.ChoiceField(label = "환경",choices = ENV_DVS_CD)

###############################################################################
class vrfyLogForm(EnvForm):
    errYn = forms.BooleanField(
        label = '오류Only',
        required=False,
        help_text='수행결과가 오류가 있는 경우'
    )        

dq/views.py
###########################################################################
#     Meta-eXpress 2.1 
#     All right reserved by wonseokyou 
#     email : wonseokyou@gmail.com 
###########################################################################
from django.http import HttpResponse, HttpResponseNotFound, HttpResponseGone, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.utils import timezone
import datetime,pytz,re #  날짜를 파싱하기위한 정규식 처리 
from django import forms

from django.conf import settings
# Create your views here.
############################## json ##############################
import json
############################## dbConn  ##############################
from .models import * 
from .forms import *
from .dbMysql import Ssh,Conn,get_db_sch_nm
############################## task  ##############################
from django.views.decorators.csrf import csrf_exempt
from logging import getLogger
from .tasks import demo_task,vrfy_task,vrfy_task_aurora

# 쿼리 OR조건을 위해서 import 함 
from django.db.models import Q
############################## Transaction 매뉴얼관리  ##############################
from django.db import transaction, connection
############################## out 테이블관리 시작 ##############################
from .out_table import trace_out_table,matrix_out_table
############################## 공통 함수 및 class  ##############################
from .funcs import * 


app_name ='dq'
########################## 공통 함수 ########################## 
def dummy(request, template_name='dummy.html'):
    data = {}
    data['object_list'] = getattr(settings, "BASE_DIR", None)
    data['app_name'] = app_name
    return render(request, template_name, data)

def base(request, template_name='base.html'):
    data = {}
    data['object_list'] = getattr(settings, "BASE_DIR", None)
    return render(request, template_name, data)
   
########################## task start ########################## 
logger = getLogger(__name__)

@csrf_exempt
def tasks(request):
    if request.method == 'POST':
        return _post_tasks(request)
    else:
        return JsonResponse({}, status=405)

def _post_tasks(request):
    message = request.POST['message']
    logger.debug('calling demo_task. message={0}'.format(message))
    demo_task(message)
    return JsonResponse({}, status=302)
 

########################## vrfy start ########################## 
def vrfy_list(request, template_name='vrfy_list.html'):
    gets = request.GET
    #print(gets)
    if ( 'qry' in gets ) :
        qry = gets['qry']
    else:
        qry = ''
    if (qry == None or len(qry) <= 2):
        vrfys = Vrfy.objects.all()
    else:
        vrfys = Vrfy.objects.filter(TABLE_NM = qry)
    data = {}
    data['object_list'] = vrfys
    data['gets'] = gets
    return render(request, template_name, data)
#---------------------------------------------------------------------
def vrfy_create(request, template_name='vrfy_form.html'):
    form = VrfyForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('dq:vrfy_list')
    return render(request, template_name, {'form':form})
#---------------------------------------------------------------------
def vrfy_update(request, pk,template_name='vrfy_form.html'):    
    vrfy = get_object_or_404(Vrfy, pk=pk)
    form = VrfyForm(request.POST or None, instance=vrfy)
    if form.is_valid():
        form.save()
        return redirect('dq:vrfy_list')
    return render(request, template_name, {'form':form,'row' : vrfy })
#---------------------------------------------------------------------
def vrfy_delete(request, pk):
    vrfy= get_object_or_404(Vrfy, pk=pk)    
    if vrfy != None :
        vrfy.delete()
        return redirect('dq:vrfy_list')
    return HttpResponse(status=405)
#---------------------------------------------------------------------
def vrfy_run(request, pk,template_name='vrfy_run.html'): 
    '''직접 수행된 결과를 보여준다'''   
    vrfy = get_object_or_404(Vrfy, pk=pk)
    sqlStr = vrfy.CMD_CNTS
    print('*'*40)
    print("시작시간 : %s" % datetime.datetime.now() )
    print('env=>','dev')
    print("작업번호 : %s" % vrfy.VRFY_NO)
    print("작업명  : %s" % vrfy.VRFY_NM)
    # print("작업내용 :\n %s" % sqlStr)
    msg = { 'result' : 'NOT_OK'}
    try:
        if ( vrfy.CMD_TYPE_CD == 'AURORA_SQL'):
            rets = run_sql(vrfy.DB_NM,vrfy.SCHEMA_NM,sqlStr)
            ret = rets['ret']
            print(ret)
            msg['result'] =  'OK'
            msg['ret'] = ret            
        else:
            msg['result'] = 'NOT_YET'
    except Exception as e:
        print(e)
    vrfyLog_create(vrfy,rets)
    return render(request, template_name, {'row' : vrfy ,'msg' : msg })
############################## SQL 수행 ###########################
def run_sql(db,schema,sqlStr):
    ret = None
    strt_dttm = timezone.now()
    try:
        conn = Conn(db)
        conn.ssh.start()
        conn.sshDbConn()
        conn.select_db(schema)
        ret = conn.execute(sqlStr)
        if (len(ret) == 0 ) :
            ret = 0 # 결과가 없으면 0으로 간주함.
        elif ( 'CNT' in ret[0]  ) :
            ret = ret[0]['CNT']
        elif ('cnt' in ret[0] )  :
            ret = ret[0]['cnt'] 
        else:
            pass
    except Exception as e:
        print(e)
        ret = 'ERR'
    finally :
        if ( conn is not None ):
            conn.close()
        end_dttm = timezone.now()         
        rets = { 'ret' : ret , 'strt_dttm' : strt_dttm, 'end_dttm' : end_dttm } 
        return rets
########################## 오로라 검증 (단건 작업 수행) ########################## 
@csrf_exempt
def vrfy_tasks(request):
    '''검증TASK를 수행한 작업을 SUBMIT 한다'''
    pk = request.GET['pk']
    if request.GET.get('env'):
        env = request.GET['env']
    else:
        env = 'dev'
    vrfy = get_object_or_404(Vrfy, pk=pk)    
    if vrfy != None :       
        logger.debug('vrfy_task({0})'.format(pk))
        message = { 'VRFY_NO': vrfy.VRFY_NO 
                  , 'env'  : env
                  }
        vrfy_task(message)
        context = { 'message' : {'DB_NM' : vrfy.DB_NM
                                , 'SCHEMA_NM' : vrfy.SCHEMA_NM
                                , 'VRFY_NO': vrfy.VRFY_NO
                                , 'VRFY_NM': vrfy.VRFY_NM
                                , 'VRFY_EXPLN' : vrfy.VRFY_EXPLN
                                , 'CMD_CNTS' : vrfy.CMD_CNTS
                                , 'VRFY_RSLT_VAL' : '작업이 정상적으로 제출되었습니다.\n Log를 확인해주세요'
                                },
                    'ret'  : 'OK'
                }
    else:
        context = { 'message' : { 'DB_NM' : '데이터없음'
                                , 'SCHEMA_NM' : '데이터없음'
                                , 'VRFY_NO': 0
                                , 'VRFY_NM': '데이터없음'
                                , 'VRFY_EXPLN' : '데이터없음'
                                , 'CMD_CNTS' : '데이터없음'
                                , 'VRFY_RSLT_VAL' :'작업제출 ERROR!!!!'
                                },
                    'ret'  : 'NOT_OK'
                } 
    return HttpResponse(json.dumps(context), content_type="application/json")
######################################################################
def vrfy_job(pk,env='dev'):
    '''TASK에 의해 수행되면 검증번호pk 작업을 수행한다.'''    
    vrfy = get_object_or_404(Vrfy, pk=pk)
    sqlStr = vrfy.CMD_CNTS
    print('*'*40)
    print("시작시간 : %s" % datetime.datetime.now() )  
    print('env=>',env)  
    print("작업번호 : %s" % vrfy.VRFY_NO)
    print("작업명  : %s" % vrfy.VRFY_NM)
    # print("작업내용 :\n %s" % sqlStr)
    msg = { 'ret' : 'NOT_OK'}
    dbNm , schNm = get_db_sch_nm(vrfy.DB_NM,vrfy.SCHEMA_NM,env)
    try:
        if ( vrfy.CMD_TYPE_CD == 'AURORA_SQL'):
            rets = run_sql(dbNm,schNm,sqlStr)
            ret = rets['ret']
            print("수행결과 : %s" % ret)  
            print("종료시간 : %s" % datetime.datetime.now() ) 
            msg['ret'] =  'OK'
            msg['run_sql_ret'] = ret
        else:
            msg['ret'] = 'NOT_YET'
            ret = -1
    except Exception as e:
        print(e)
        ret = -1
    vl = vrfyLog_create(vrfy,rets,env)
    return JsonResponse( {'ret' : msg['ret'] , 'VRFY_NO' : vrfy.VRFY_NO, 'VRFY_LOG_NO' : vl.VRFY_LOG_NO },status=302)
########################## 오로라 검증 스케쥴 ########################## 
@csrf_exempt
def vrfy_tasks_aurora(request):
    try:
        if request.method == 'POST':
            env = request.POST['env']
            if env not in [ 'dev','tst','prd'] :
                raise Exception('env is %s , env must be 1 of dev,tst,prd!!' % env)
            print('*'*40)
            print('오로라 데이터 품질 검증 배치 수행')
            print('env=>',env)
            print('*'*40)   
            vrfy_task_aurora({'env' : env })
            return JsonResponse({'ret' : 'OK'}, status=302)
    except Exception as e :    
        return JsonResponse({'ret' : 'NOK_OK', 'msg' : e }, status=405)   

def vrfy_job_aurora(env):
    '''명령유형코드중 AURORA_SQL을 찾아서 모두 수행한다.'''
    vs = Vrfy.objects.filter(Q(CMD_TYPE_CD = 'AURORA_SQL') & Q(USE_YN = 'Y') )
    for i in vs:
        vrfy_job(i.VRFY_NO,env)
    return True

########################## vrfy Log ##########################
def vrfyLog_list(request, template_name='vrfyLog_list.html'):
    gets = request.GET
    #print(gets)    
    qry = gets['qry'] if ( 'qry' in gets ) else ''
    dates = gets['dates'] if ( 'dates' in gets ) else '' 
    date1, date2, dt_ary = get_datetime_range(dates)
    if (qry == None or len(qry) < 1):
        if ( date1 == None or date2 == None ):
            vrfyLogs = VrfyLog.objects.all()
        else:
            vrfyLogs = VrfyLog.objects.exclude(MODI_DTTM__lt=date1).exclude(MODI_DTTM__gt=date2)            
    else:
        if ( date1 == None or date2 == None ):
            vrfyLogs = VrfyLog.objects.filter(VRFY_NO=qry)
        else:
            vrfyLogs = VrfyLog.objects.filter(VRFY_NO=qry).exclude(MODI_DTTM__lt=date1).exclude(MODI_DTTM__gt=date2)

    data = {}
    data['gets'] = gets

dq/templates/ilm_list.html
{% extends "base.html" %}

{% block include_datatable %}
{% include "datatable.html" %}
{% include "angular.html" %}
{% endblock %}

{% block content %}
<div style="margin-left:5%;margin-right:5%">
    <div class="padding-20">
        <div class="row">
            <div class="col-md-2">
                    <h3>{% block title %}정보수명관리{% endblock %}</h3>
            </div>
            <div class="col-md-8">                
                <!-- Search Bar -->
                <form class="navbar-form navbar-left" role="search" method=GET>
                        <div class="form-group">
                            <label for="Search">테이블명:</label>
                            <input type="text" class="form-control" placeholder="Search" name=qry id=qry value="{{gets.qry}}" >
                        </div>
                        <button type="submit" class="btn btn-default">조회</button>
                </form>
            </div>       
        </div>
        <div class="row" >            
            <div class="col-md-1">
                    <a href="{% url 'dq:ilm_new' %}" class="btn btn-primary" role="button" ><span class="glyphicon glyphicon-plus-sign"></span> New</a>                
            </div> 
        </div>
    </div>
    <div id="content" class="padding-20">
        <!-- HTML DATATABLE -->
        <table class="table table-striped table-hover table-bordered" id="example">
            <thead>
                <tr>
                    <th>ID</th>                
                    <th>대분류</th>
                    <th>중분류</th>
                    <th>ILM명</th> 
                    <th>수행로그</th>                                  
                    <th>테이블명</th>
                    <th>ILM설명</th>
                    <th>ILM순번</th>
                    <th>ILM유형코드</th>
                    <th>명령유형코드</th>
                    <!--th>등록자아이디</th-->
                    <!--th>등록일시</th-->
                    <th>수정자아이디</th>
                    <th>수정일시</th>
                    <!--th class="hideTechDetail"></th-->
                </tr>
            </thead>
            <tbody>
                {% for row in object_list %}
                <tr>
                    <td><a href="{% url 'dq:ilm_edit' row.ILM_NO  %}"><span class="glyphicon glyphicon-edit"></span> {{ row.ILM_NO }}</a></td>             
                    <td>{{ row.CLSF_NM1 }}</td>
                    <td>{{ row.CLSF_NM2 }}</td>
                    <td>{{ row.ILM_NM }}</td> 
                    <td><a  href="{% url  'dq:vrfyLog_list' %}?qry={{ row.ILM_NO }}"><button type="button" class="btn btn-info">Log</button></a></td>                                   
                    <td>{{ row.TABLE_NM }}</td>
                    <td>{{ row.ILM_EXPLN }}</td>
                    <td>{{ row.ILM_SEQ }}</td>
                    <td>{{ row.ILM_TYPE_CD }}</td>                    
                    <td>{{ row.CMD_TYPE_CD }}</td>                       
                    <!--td>{# row.RGSTR_ID #}</td-->
                    <!--td>{# row.RGST_DTTM|date:'Y-m-d'  #}</td-->                
                    <td>{{ row.MODR_ID }}</td>
                    <td>{{ row.MODI_DTTM|date:'Y-m-d'  }}</td>  
                    <!--td class="hideTechDetail">{% csrf_token %}</td-->
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript" class="init">
    $(document).ready(function() {
        $('#example').DataTable( {          
            dom: 'Bfrtpi', //lBfrtpi
                buttons: [
                    'copy', 'csv', 'excel', 'pdf', 'print'
                ],
            "columns": [
                { "width": "5%" },
                { "width": "5%" },
                { "width": "5%" },
                { "width": "15%" },
                { "width": "5%" },
                { "width": "15%" },
                { "width": "15%" },
                { "width": "5%" },
                { "width": "10%" },
                { "width": "5%" },
                { "width": "5%" },
                { "width": "5%" }
            ],                  
            "lengthMenu": [
                [5, 15, 20, -1],
                [5, 15, 20, "All"]
            ],
            "pageLength": 15,    
            "columnDefs": [{
                "targets": [0],
                "searchable": false,
                "visible": true,
                "width": "20%"
            }, {
                "targets": [ 1 ],
                "searchable": false,
                "visible": true,
            }],                   
            "paging":   true,
            "ordering" : true,
            "order": [[ 0, "desc" ]],
            "info":     true
        } );
    } );
</script>

{% block include_modal %}
{% include "vrfyLog_ajax.html" %}
{% endblock %}

{% endblock content %}

dq/templates/vrfy_list.html
{% extends "base.html" %}

{% block include_datatable %}
{% include "datatable.html" %}
{% endblock %}

{% block content %}
<div style="margin-left:5%;margin-right:5%">
    <div class="padding-20">
        <div class="row">
            <div class="col-md-2">
                    <h3>{% block title %}검증{% endblock %}</h3>
            </div>
            <div class="col-md-8">                
                <!-- Search Bar -->
                <form class="navbar-form navbar-left" role="search" method=GET>
                        <div class="form-group">
                            <label for="Search">테이블명:</label>
                            <input type="text" class="form-control" placeholder="Search" name=qry id=qry value="{{gets.qry}}" >
                        </div>
                        <button type="submit" class="btn btn-default">조회</button>
                </form>
            </div>       
        </div>
        <div class="row" >            
            <div class="col-md-1">
                    <a href="{% url 'dq:vrfy_new' %}" class="btn btn-primary" role="button" ><span class="glyphicon glyphicon-plus-sign"></span> New</a>                
            </div> 
        </div>
    </div>
    <div id="content" class="padding-20">
        <!-- HTML DATATABLE -->
        <table class="table table-striped table-hover table-bordered" id="example">
            <thead>
                <tr>
                    <th>ID</th>                
                    <th>대분류</th>
                    <th>중분류</th>
                    <th>검증명</th> 
                    <th>수행로그</th>                                  
                    <th>테이블명</th>
                    <th>테이블한글명</th>
                    <th>검증유형상세코드</th>
                    <th>명령유형코드</th>
                    <th>명령수행</th>
                    <!--th>등록자아이디</th-->
                    <!--th>등록일시</th-->
                    <th>수정자아이디</th>
                    <th>수정일시</th>
                    <!--th class="hideTechDetail"></th-->
                </tr>
            </thead>
            <tbody>
                {% for row in object_list %}
                <tr>
                    <td><a href="{% url 'dq:vrfy_edit' row.VRFY_NO  %}"><span class="glyphicon glyphicon-edit"></span> {{ row.VRFY_NO }}</a></td>             
                    <td>{{ row.CLSF_NM1 }}</td>
                    <td>{{ row.CLSF_NM2 }}</td>
                    <td>{{ row.VRFY_NM }}</td> 
                    <td><a  href="{% url  'dq:vrfyLog_list' %}?qry={{ row.VRFY_NO }}"><button type="button" class="btn btn-info">Log</button></a></td>                                   
                    <td>{{ row.TABLE_NM }}</td>
                    <td>{{ row.TABLE_HANGL_NM }}</td>
                    <td>{{ row.VRFY_TYPE_CD }}</td>                    
                    <td>{{ row.CMD_TYPE_CD }}</td>
                    {% if row.CMD_TYPE_CD == 'AURORA_SQL' %}
                        <td onClick="run_vrfy('{{ row.VRFY_NM }}',{{ row.VRFY_NO }})" ><button type="button" class="btn btn-warning">Run</button></td>             
                    {% else %}
                        <td></td>
                    {% endif %}                    
                
                    <!--td>{# row.RGSTR_ID #}</td-->
                    <!--td>{# row.RGST_DTTM|date:'Y-m-d'  #}</td-->                
                    <td>{{ row.MODR_ID }}</td>
                    <td>{{ row.MODI_DTTM|date:'Y-m-d'  }}</td>  
                    <!--td class="hideTechDetail">{% csrf_token %}</td-->
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript" class="init">
    $(document).ready(function() {
        $('#example').DataTable( {          
            dom: 'Bfrtpi', //lBfrtpi
                buttons: [
                    'copy', 'csv', 'excel', 'pdf', 'print'
                ],
            "columns": [
                { "width": "5%" },
                { "width": "5%" },
                { "width": "5%" },
                { "width": "15%" },
                { "width": "5%" },
                { "width": "15%" },
                { "width": "15%" },
                { "width": "5%" },
                { "width": "10%" },
                { "width": "5%" },
                { "width": "5%" },
                { "width": "5%" }
            ],                  
            "lengthMenu": [
                [5, 15, 20, -1],
                [5, 15, 20, "All"]
            ],
            "pageLength": 15,    
            "columnDefs": [{
                "targets": [0],
                "searchable": false,
                "visible": true,
                "width": "20%"
            }, {
                "targets": [ 1 ],
                "searchable": false,
                "visible": true,
            }],                   
            "paging":   true,
            "ordering" : true,
            "order": [[ 0, "desc" ]],
            "info":     true
        } );
    } );
</script>

{% block include_modal %}
{% include "vrfyLog_ajax_run.html" %}
{% endblock %}

{% endblock content %}