blog/urls.py
from django.conf.urls import url
from . import views

app_name='blog'
urlpatterns = [
    #url(r'^$', views.post_list, name='post_list'),
    url(r'^$', views.PagesView.as_view(), name='pages'),    
    url(r'page/(?P<pk>\d+)/$', views.post_page, name='post_page'),    
    url(r'post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'post/new/$', views.post_new, name='post_new'),
    url(r'post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'drafts/$', views.post_draft_list, name='post_draft_list'),
    url(r'post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    #url(r'accounts/login/$', views.login, name='login'),
    #url(r'accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),  
      
]

demo/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from .views import HomePageView, FormHorizontalView, FormInlineView, PaginationView, FormWithFilesView, \
    DefaultFormView, MiscView, DefaultFormsetView, DefaultFormByFieldView, AngularView

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^formset$', DefaultFormsetView.as_view(), name='formset_default'),
    url(r'^form$', DefaultFormView.as_view(), name='form_default'),
    url(r'^form_by_field$', DefaultFormByFieldView.as_view(), name='form_by_field'),
    url(r'^form_horizontal$', FormHorizontalView.as_view(), name='form_horizontal'),
    url(r'^form_inline$', FormInlineView.as_view(), name='form_inline'),
    url(r'^form_with_files$', FormWithFilesView.as_view(), name='form_with_files'),
    url(r'^pagination$', PaginationView.as_view(), name='pagination'),
    url(r'^misc$', MiscView.as_view(), name='misc'),
    url(r'^angular$', AngularView.as_view(), name='angular'),
]

dq/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url
from . import views
############################## bootstrap 3 ##############################
######################################################################################

app_name ='dq'
urlpatterns = [
    url(r'^dummy', views.dummy, name='dummy'),    
    url(r'^base', views.base, name='base'),

    url(r'^$', views.base, name='base'),     
    #vrfy
    url(r'^vrfys', views.vrfy_list, name='vrfy_list'),
    url(r'^vrfy/create$', views.vrfy_create, name='vrfy_new'),
    url(r'^vrfy/update/(?P<pk>\d+)', views.vrfy_update, name='vrfy_edit'),
    url(r'^vrfy/delete/(?P<pk>\d+)', views.vrfy_delete, name='vrfy_delete'),
    # 오로가 검증대상을 일괄로 수행해줌   
    # curl -d env=dev http://localhost:8001/dq/vrfy/tasks_aurora/
    url(r'^vrfy/tasks_aurora/', views.vrfy_tasks_aurora, name='vrfy_tasks_aurora'),  

    url(r'^vrfy/tasks/', views.vrfy_tasks, name='vrfy_tasks'),    
    url(r'^vrfy/job/(?P<pk>\d+)', views.vrfy_job, name='vrfy_job'),
    url(r'^vrfy/run/(?P<pk>\d+)', views.vrfy_run, name='vrfy_run'),
    #vrfyLog 
    url(r'^vrfyLog_ajax/', views.vrfyLog_ajax, name='vrfyLog_ajax'),     
    url(r'^vrfyLog_ajax_view/', views.vrfyLog_ajax_view, name='vrfyLog_ajax_view'),
    url(r'^vrfyLogs', views.vrfyLog_list, name='vrfyLog_list'),

    #TableCopy
    url(r'^tblCpys2', views.tblCpy_list2, name='tblCpy_list2'),    
    url(r'^tblCpys', views.tblCpy_list, name='tblCpy_list'),
    url(r'^tblCpy_ajax', views.tblCpy_ajax, name='tblCpy_ajax'),
    url(r'^tblCpy/create$', views.tblCpy_create, name='tblCpy_new'),
    url(r'^tblCpy/update/(?P<pk>\d+)', views.tblCpy_update, name='tblCpy_edit'),
    url(r'^tblCpy/delete/(?P<pk>\d+)', views.tblCpy_delete, name='tblCpy_delete'),

    #ilm(information lifecycle mgmt.)
    url(r'^ilms', views.ilm_list, name='ilm_list'),
    url(r'^ilm/create$', views.ilm_create, name='ilm_new'),
    url(r'^ilm/update/(?P<pk>\d+)', views.ilm_update, name='ilm_edit'),
    url(r'^ilm/delete/(?P<pk>\d+)', views.ilm_delete, name='ilm_delete'),
    
    #task
    url(r'^tasks', views.tasks, name='tasks'),
    #vrfyCmd
    url(r'^vrfy_Cmds', views.vrfy_Cmd_list, name='vrfy_Cmd_list'),
    url(r'^vrfy_Cmd/create$', views.vrfy_Cmd_create, name='vrfy_Cmd_new'),
    url(r'^vrfy_Cmd/update/(?P<pk>\d+)', views.vrfy_Cmd_update, name='vrfy_Cmd_edit'),
    url(r'^vrfy_Cmd/delete/(?P<pk>\d+)', views.vrfy_Cmd_delete, name='vrfy_Cmd_delete'),       
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^mdl2tbl/', include('mdl2tbl.urls')),
    url(r'^dq/', include('dq.urls')), 
    #url(r'^erd/', include('erd.urls')),     
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^', include('demo.urls')),    
]

blog/models.py
from django.db import models

# Create your models here.
from django.utils import timezone


class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(
            default=timezone.now)
    published_date = models.DateTimeField(
            blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text',)


class QForm(forms.Form):
    """
    컬럼명을 입력받는다.
    """

    q = forms.CharField()

    # TODO: Re-enable this after Django 1.11 #28105 is available
    # polygon = gisforms.PointField()

    required_css_class = 'bootstrap3-req'

    # Set this to allow tests to work properly in Django 1.10+
    # More information, see issue #337
    use_required_attribute = False

    def clean(self):
        cleaned_data = super(TestForm, self).clean()
        raise forms.ValidationError(
            "This error was added to show the non field errors styling.")
        return cleaned_data 

blog/views.py
import os
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.template import loader
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Post
from .forms import PostForm

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic.base import TemplateView
# 쿼리 OR조건을 위해서 import 함 
from django.db.models import Q

# Create your views here.
def post_list(request):
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-id')
    #posts = Post.objects.order_by('published_date')
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    #print(os.path.join(BASE_DIR, 'templates'))
    return render(request, 'blog/post_list.html', {'posts': posts})

class PagesView(TemplateView):
    '''객체형태로 page 목록을 출력함'''
    template_name = 'blog/pages.html'

    def get_context_data(self, **kwargs):
        context = super(PagesView, self).get_context_data(**kwargs)
        # 검색 조건 추가 시작 
        q = self.request.GET.get('q')
        if q : 
            posts = Post.objects.filter(Q(title__contains=q) |Q(text__contains=q) ).order_by('-id')
        else:
            posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-id')
        context['q'] = q if q != None else ""
        context['q_str'] = 'q=' + q if q!= None else ""            
        # 검색조건 추가 종료
        paginator = Paginator(posts, 10)
        page = self.request.GET.get('page')
        try:
            show_posts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            show_posts = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            #show_posts = paginator.page(paginator.num_pages)
            show_posts = paginator.page(1)
        context['posts'] = show_posts
        return context

def post_page(request, pk=1):
    '''함수형태로 page 목록을 출력함'''
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-id')
    paginator = Paginator(posts, 10) # Show 10 contacts per page
    page = pk
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post_page.html', {'posts': posts })

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})
    #return render(request, 'blog/test.html',{'post': post })

def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)            
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('blog:post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('created_date')
    return render(request, 'blog/post_draft_list.html', {'posts': posts})

def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:post_detail', pk=pk)

def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blog:post_list')

blog/templates/blog/base.html
{% load staticfiles %}
<html>
    <head>
        <title>Django Test blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="page-header">
            {% if user.is_authenticated %}
                <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
                <a href="{% url 'blog:post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
                <p class="top-menu">Hello {{ user.username }} <small>(<a href="{% url 'blog:logout' %}">Log out</a>)</small></p>
            {% else %}
                <a href="{% url 'blog:login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
            {% endif %}
            <h1><a href="/blog">Django Test Blog</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

blog/templates/blog/base_x.html
{% load staticfiles %}
<html>
    <head>
        <title>Django Test blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="page-header">
            {% if user.is_authenticated %}
                <a href="{% url 'blog:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
                <a href="{% url 'blog:post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
                <p class="top-menu">Hello {{ user.username }} <small>(<a href="{% url 'blog:logout' %}">Log out</a>)</small></p>
            {% else %}
                <a href="{% url 'blog:login' %}" class="top-menu"><span class="glyphicon glyphicon-lock"></span></a>
            {% endif %}
            <h1><a href="/blog">Meta-eXpress Blog</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

blog/templates/blog/pages.html
{% extends 'base.html' %}

{% load bootstrap3 %}

{% block title %}
    게시글
{% endblock %}

{% block content %}
<div class="container">

        <div class="row">
            <div class="col-md-6"></div>
            <div class="col-md-6">
                <span class="pull-right">
                        <!-- 검색조건 시작 -->
                        <form action="?page={{posts.page.number}}" method="get" class="form-inline">
                                <div class="form-group bootstrap3-required"> 
                                    <label for="Search">검색어:</label>        
                                    <div class="form-group bootstrap3-req">
                                        <label class="sr-only" for="q">검색어</label>
                                        <input type="text" name="q" placeholder="검색어" id="q" title="" class="form-control" value="{{q}}">
                                    </div>
                                    <div class="form-group">
                                        <button type="submit" class="btn btn-primary" layout="inline"> 
                                        <span class="glyphicon glyphicon-search"></span> 검색
                                        </button>
                                    </div>
                                    <div class="form-group">
                                        <a class="btn btn-info" href="{% url 'blog:post_new' %}" ><span class="glyphicon glyphicon-plus-sign"></span> New</a>
                                    </div>
                                </div>
                            </form> 
                        <!-- 검색조건 종료 -->        
                </span>
            </div>
        </div>
        <br>
        <!-- 테이블 시작 -->  
        <table id="example" class="display table table-striped table-bordered" cellspacing="0" width="100%" >
            <thead>
            <tr >
                <th style="width:10%;text-align:center" >번호</th>
                <th style="width:50%;text-align:center">제목</th>
                <th style="width:20%;text-align:center" >등록자</th>
                <th style="width:20%;text-align:center" >수정일시</th>
            </tr>
            </thead>
            <tbody>
                    {% for post in posts %}
                    <tr>
                        <td> {{ post.id }} </td>
                        <td> <a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></td>
                        <td> {{ post.author.username }} </td>
                        <td> {{ post.published_date }} </td>
                    </tr>
                    {% endfor %}
            <tbody>
        </table> 
        <!-- 테이블 종료 -->  
        <!-- pagination 시작 -->
        <div class="row text-center">
        {% bootstrap_pagination posts url="?flop=flip" extra=q_str size="small" %}
        </div>
        <!-- pagination 종료 -->
    </div>    
    <hr>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% else %}
            <a class="btn btn-default" href="{% url 'blog:post_publish' %}">Publish</a>            
        {% endif %}            
        <a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
        <a class="btn btn-default" href="{% url 'blog:post_remove' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
        <a class="btn btn-default" href="{% url 'blog:pages' %}"><span class="glyphicon glyphicon glyphicon-th-list"></span></a>
        <h2>{{ post.title }}</h2>
        <p>{{ post.text|safe }}</p>
    </div>
</div>    
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <p class="date">created: {{ post.created_date|date:'Y-m-d' }}</p>
            <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{ post.title }}</a></h1>
            <p>{{ post.text|truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock %}

blog/templates/blog/post_edit.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block include_datatable %}
{% include "ckeditor.html" %}
{% endblock %}
{% block content %}
<div class="container">
    <h3>편집</h3>
    <form method="POST" class="post-form">{% csrf_token %}
        {# form.as_p #}
        {% bootstrap_form form %}
        <div class="row">
                <div class="col-md-6"></div>
                <div class="col-md-6">
                    <span class="pull-right">
                        <button type="submit" class="save btn btn-default">Save</button>
                    </span>
                </div>
            </div>  
        
    </form>
</div>
<script>
    CKEDITOR.replace( 'id_text' );
</script>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6"></div>
        <div class="col-md-6">
            <span class="pull-right">
                 <a class="btn btn-primary" href="{% url 'blog:post_new' %}" style="margin-bottom:5px" ><span class="glyphicon glyphicon-plus-sign"></span> New</a>
            </span>
        </div>
    </div>        
    <table id="example" class="display table table-striped table-bordered" cellspacing="0" width="100%" >
        <thead>
        <tr >
            <th style="width:10%;text-align:center" >번호</th>
            <th style="width:50%;text-align:center">제목</th>
            <th style="width:20%;text-align:center" >등록자</th>
            <th style="width:20%;text-align:center" >수정일시</th>
        </tr>
        </thead>
        <!-- 이 부분이 바뀌었습니다 -->
        <tbody>
                {% for post in posts %}
                <tr>
                    <td> {{ post.id }} </td>
                    <td> <a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></td>
                    <td> {{ post.author.username }} </td>
                    <td> {{ post.published_date }} </td>
                </tr>
                {% endfor %}
        <!-- 여기까지 -->
        <tbody>
    </table>    
</div>    
{% endblock %}

blog/templates/blog/post_page.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% block title %}
    게시글
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6"></div>
        <div class="col-md-6">
            <span class="pull-right">
                 <a class="btn btn-primary" href="{% url 'blog:post_new' %}" style="margin-bottom:5px" ><span class="glyphicon glyphicon-plus-sign"></span> New</a>
            </span>
        </div>
    </div>
    <!-- 테이블 시작 -->        
    <table id="example" class="display table table-striped table-bordered" cellspacing="0" width="100%" >
        <thead>
        <tr >
            <th style="width:10%;text-align:center" >번호</th>
            <th style="width:50%;text-align:center">제목</th>
            <th style="width:20%;text-align:center" >등록자</th>
            <th style="width:20%;text-align:center" >수정일시</th>
        </tr>
        </thead>
        <tbody>
                {% for post in posts %}
                <tr>
                    <td> {{ post.id }} </td>
                    <td> <a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></td>
                    <td> {{ post.author.username }} </td>
                    <td> {{ post.published_date }} </td>
                </tr>
                {% endfor %}
        <tbody>
    </table>
    <!-- 테이블 종료 -->  
    <!-- pagination 시작 -->
    <div class="row text-center">
        <ul class="pagination">
            {% for i in posts.paginator.page_range %}
                {% ifequal i posts.number %}
                    <li class="active" ><a href="#">{{i}}</a></li>
                {% else %}
                    <li><a href="{% url 'blog:post_page' i %}">{{i}}</a></li>
                {% endifequal %}
            {% endfor %}
        </ul>
    </div>
    <!-- pagination 종료 -->    
</div>    
{% endblock %}

blog/templates/blog/test.html
<p>
    이것은 테스트 화면입니다.
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% else %}
            <a class="btn btn-default" href="{ % url 'blog:post_publish' % }">Publish</a>            
        {% endif %}            
        <a class="btn btn-default" href="{ % url 'blog:post_edit' pk=post.pk % }"><span class="glyphicon glyphicon-pencil"></span></a>
        <a class="btn btn-default" href="{ % url 'blog:post_remove' pk=post.pk % }"><span class="glyphicon glyphicon-remove"></span></a>
        <h1>{{ post.title }}</h1>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>   
</p>