blog/urls.py
from django.conf.urls import url
from . import views

app_name='blog'
urlpatterns = [
    #url(r'^$', views.post_list, name='post_list'),
    url(r'^$', views.PagesView.as_view(), name='pages'),    
    url(r'page/(?P<pk>\d+)/$', views.post_page, name='post_page'),    
    url(r'post/(?P<pk>\d+)/$', views.post_detail, name='post_detail'),
    url(r'post/new/$', views.post_new, name='post_new'),
    url(r'post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'drafts/$', views.post_draft_list, name='post_draft_list'),
    url(r'post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),
    url(r'post/(?P<pk>\d+)/remove/$', views.post_remove, name='post_remove'),
    #url(r'accounts/login/$', views.login, name='login'),
    #url(r'accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),  
      
]

demo/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url

from .views import HomePageView, FormHorizontalView, FormInlineView, PaginationView, FormWithFilesView, \
    DefaultFormView, MiscView, DefaultFormsetView, DefaultFormByFieldView, AngularView

urlpatterns = [
    url(r'^$', HomePageView.as_view(), name='home'),
    url(r'^formset$', DefaultFormsetView.as_view(), name='formset_default'),
    url(r'^form$', DefaultFormView.as_view(), name='form_default'),
    url(r'^form_by_field$', DefaultFormByFieldView.as_view(), name='form_by_field'),
    url(r'^form_horizontal$', FormHorizontalView.as_view(), name='form_horizontal'),
    url(r'^form_inline$', FormInlineView.as_view(), name='form_inline'),
    url(r'^form_with_files$', FormWithFilesView.as_view(), name='form_with_files'),
    url(r'^pagination$', PaginationView.as_view(), name='pagination'),
    url(r'^misc$', MiscView.as_view(), name='misc'),
    url(r'^angular$', AngularView.as_view(), name='angular'),
]

dq/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url
from . import views
############################## bootstrap 3 ##############################
######################################################################################

app_name ='dq'
urlpatterns = [
    url(r'^dummy', views.dummy, name='dummy'),    
    url(r'^base', views.base, name='base'),

    url(r'^$', views.base, name='base'),     
    #vrfy
    url(r'^vrfys', views.vrfy_list, name='vrfy_list'),
    url(r'^vrfy/create$', views.vrfy_create, name='vrfy_new'),
    url(r'^vrfy/update/(?P<pk>\d+)', views.vrfy_update, name='vrfy_edit'),
    url(r'^vrfy/delete/(?P<pk>\d+)', views.vrfy_delete, name='vrfy_delete'),
    # 오로가 검증대상을 일괄로 수행해줌   
    # curl -d env=dev http://localhost:8001/dq/vrfy/tasks_aurora/
    url(r'^vrfy/tasks_aurora/', views.vrfy_tasks_aurora, name='vrfy_tasks_aurora'),  

    url(r'^vrfy/tasks/', views.vrfy_tasks, name='vrfy_tasks'),    
    url(r'^vrfy/job/(?P<pk>\d+)', views.vrfy_job, name='vrfy_job'),
    url(r'^vrfy/run/(?P<pk>\d+)', views.vrfy_run, name='vrfy_run'),
    #vrfyLog 
    url(r'^vrfyLog_ajax/', views.vrfyLog_ajax, name='vrfyLog_ajax'),     
    url(r'^vrfyLog_ajax_view/', views.vrfyLog_ajax_view, name='vrfyLog_ajax_view'),
    url(r'^vrfyLogs', views.vrfyLog_list, name='vrfyLog_list'),

    #TableCopy
    url(r'^tblCpys2', views.tblCpy_list2, name='tblCpy_list2'),    
    url(r'^tblCpys', views.tblCpy_list, name='tblCpy_list'),
    url(r'^tblCpy_ajax', views.tblCpy_ajax, name='tblCpy_ajax'),
    url(r'^tblCpy/create$', views.tblCpy_create, name='tblCpy_new'),
    url(r'^tblCpy/update/(?P<pk>\d+)', views.tblCpy_update, name='tblCpy_edit'),
    url(r'^tblCpy/delete/(?P<pk>\d+)', views.tblCpy_delete, name='tblCpy_delete'),

    #ilm(information lifecycle mgmt.)
    url(r'^ilms', views.ilm_list, name='ilm_list'),
    url(r'^ilm/create$', views.ilm_create, name='ilm_new'),
    url(r'^ilm/update/(?P<pk>\d+)', views.ilm_update, name='ilm_edit'),
    url(r'^ilm/delete/(?P<pk>\d+)', views.ilm_delete, name='ilm_delete'),
    
    #task
    url(r'^tasks', views.tasks, name='tasks'),
    #vrfyCmd
    url(r'^vrfy_Cmds', views.vrfy_Cmd_list, name='vrfy_Cmd_list'),
    url(r'^vrfy_Cmd/create$', views.vrfy_Cmd_create, name='vrfy_Cmd_new'),
    url(r'^vrfy_Cmd/update/(?P<pk>\d+)', views.vrfy_Cmd_update, name='vrfy_Cmd_edit'),
    url(r'^vrfy_Cmd/delete/(?P<pk>\d+)', views.vrfy_Cmd_delete, name='vrfy_Cmd_delete'),       
]

mdl2tbl/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url
from . import views
############################## bootstrap 3 ##############################
#from .views import HomePageView,DefaultFormView,Djbs01FormView,Djbs02FormView,Djbs03FormView,Djbs04FormView,Djbs05FormView,Djbs06FormView,Djbs07FormView
######################################################################################

app_name='mdl2tbl'
urlpatterns = [
    url(r'^$',  views.Djbs02FormView.as_view(), name='djbs02'),
    url(r'form_by_field', views.form_by_field , name='form_by_field'),
    url(r'djbs01', views.Djbs01FormView.as_view(), name='djbs01'),
    url(r'djbs02', views.Djbs02FormView.as_view(), name='djbs02'),
    url(r'djbs03', views.Djbs03FormView.as_view(), name='djbs03'),
    url(r'djbs04', views.Djbs04FormView.as_view(), name='djbs04'),
    url(r'djbs05', views.Djbs05FormView.as_view(), name='djbs05'),
    url(r'djbs06', views.Djbs06FormView.as_view(), name='djbs06'),
    url(r'djbs07', views.Djbs07FormView.as_view(), name='djbs07'),
    url(r'djbs08', views.Djbs08FormView.as_view(), name='djbs08'),
    url(r'djbs09', views.Djbs09FormView.as_view(), name='djbs09'),
    url(r'djbs10', views.Djbs10FormView.as_view(), name='djbs10'),
    url(r'djbs11', views.Djbs11FormView.as_view(), name='djbs11'),
    url(r'djbs12', views.Djbs12FormView.as_view(), name='djbs12'),
    url(r'djbs13', views.Djbs13FormView.as_view(), name='djbs13'),
    url(r'djbs14', views.Djbs14FormView.as_view(), name='djbs14'),
    url(r'form', views.DefaultFormView.as_view(), name='form'),
    url(r'test/', views.tbl_list, name='tbl_list'),
    url(r'cds/', views.cd_list, name='cd_list'),    
    url(r'comp/(?P<pk>\w*)', views.comp_list, name='comp_list'),
    url(r'erd/(?P<pk>\w*)', views.erd_pview, name='erd_pview'),
]

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/', include('polls.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^mdl2tbl/', include('mdl2tbl.urls')),
    url(r'^dq/', include('dq.urls')), 
    #url(r'^erd/', include('erd.urls')),     
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^', include('demo.urls')),    
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    #url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    #url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    #url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),      
]

templates/angular.html
<!-- angular include start -->
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
<!-- angular include end --> 

templates/base.html
{% load bootstrap3 %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    {% load static %}
    <title>{% block title %} Data Life Cycle 관리 {% endblock %}</title>
    <meta name="description" content="Data Quality Meta Manager">
    <meta name="author" content="wonseokyou">
    <meta name="email" content="wsyou@wizbase.co.kr">

 <!-- jquery include start -->   
 <script src="//code.jquery.com/jquery.min.js"></script>
 
 <!-- bootstrap include start -->   
 <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
 <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
 {% block include_datatable %}{% endblock %}
</head>

<body>
  <div class="container">
  <br>
    {% block menu %} {% include "menu.html" %} {% endblock %}
    {% autoescape off %}{% bootstrap_messages %}{% endautoescape %}
  </div>
{% block content %}{% endblock %}
</body>
</html>

templates/bootstrap.html
{% extends 'bootstrap3/bootstrap3.html' %}

{% block bootstrap3_title %}{% block title %}{% endblock %}{% endblock %}

templates/cd_ajax.html
<style>
    .yws_pnt { cursor: pointer; }
</style>
<div class="span4 proj-div" data-toggle="modal" data-target="#GSCCModal"></div>
<div id="ywsModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;  </button>
            <h4 class="modal-title" id="ywsModalTitle">Modal title</h4>
        </div>
        <div class="modal-body" id="ywsModalBody">
            Modal Body
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
        </div>
    </div>
</div>
</div>
<script type="text/javascript">
function get_cd_list(myTitle,myCD) {

      $.ajax({
        url: "{%  url 'mdl2tbl:cd_list'  %}",
        data: {
          'cd': myCD
        },
        dataType: 'json',
        success: function (data) {
          //console.log(data);          
          if (data.ret == "OK") {
            showMyModal(myTitle,data.message);
          }
        }
      });
    }
// script for modal popup 
function showMyModal(myTitle, rows) {

   /*
    * '#myModayTitle' and '#myModalBody' refer to the 'id' of the HTML tags in
    * the modal HTML code that hold the title and body respectively. These id's
    * can be named anything, just make sure they are added as necessary.
    *
    */
    myHtml = ""
    for ( i in rows ) { 
        myHtml += "<tr><td>" + rows[i].CD + "</td><td>" + rows[i].CD_NM + "</td></tr>" ;
    }
    //console.log(myHtml);

    myBodyHtml = "";
    myBodyHtml += "<table class=\"display table table-striped table-bordered\" >";
    myBodyHtml += "<tr><th>코드값</th><th>코드명</th></tr>";    

    if ( myHtml != "" ) {
        myBodyHtml += myHtml;
    } else {
        // 값이 없을때 대비해서 dummy 출력 
        myBodyHtml += "<tr>";        
        // CD명 정보 
        myBodyHtml += "<td>" +  "데이터 없음" +  "</td>";
        // CD 정보 
        myBodyHtml += "<td>" +  "데이터 없음" +  "</td>";
        myBodyHtml += "</tr>";        
    }
    myBodyHtml += "</table>";
            
   $('#ywsModalTitle').html(myTitle);
   $('#ywsModalBody').html(myBodyHtml);
   
   $('#ywsModal').modal('show');
}
</script>

templates/cd_angular.html
<style>
    .yws_pnt { cursor: pointer; }
</style>
<div class="span4 proj-div" data-toggle="modal" data-target="#GSCCModal"></div>
<div id="ywsModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;  </button>
            <h4 class="modal-title" id="ywsModalTitle">Modal title</h4>
        </div>
        <div class="modal-body" id="ywsModalBody" >            
                {% verbatim %}    
                <table class="display table table-striped table-bordered" >
                    <tr>
                        <th ng-click="orderByMe('CD')" >코드값</th> 
                        <th ng-click="orderByMe('CD_NM')" >코드명</th>
                    </tr>    
                    <tr ng-repeat="x in rows | orderBy:myOrderBy ">
                      <td>{{ x.CD }}</td>
                      <td>{{ x.CD_NM }}</td>
                    </tr>
                    <div ng-if="row.length == 0">
                            <tr ng-show="!rows.length">
                                    <td><b>데이터 없음</b></td>
                                    <td><b>데이터 없음</b></td>                        
                            </tr>
                    </div>

                </table>
                {% endverbatim %}
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
        </div>
    </div>
</div>
</div> <!-- end of Angular tag -->
<script type="text/javascript">
    var app = angular.module('myApp', []);
    app.controller('myCtrl', function($scope, $http) {
        $scope.get_cd_list = function(myTitle,myCD) {
            //$http.get("mdl2tbl/cds/?cd="+myCD)
            $http({
                method : 'GET',
                url :  "{%  url 'mdl2tbl:cd_list'  %}",
                params :  { cd : myCD }
            })
            .then(function (response) {
                $scope.rows = response.data.message;
                // $scope.content = response.data;
                // $scope.statuscode = response.status;
                // $scope.statustext = response.statusText; 
            }, function(response) {
                //Second function handles error
                $scope.rows = { 'CD' : "데이터 없음", 'CD_NM' : '데이터 없음' };
            });
            showMyModal(myTitle);
        }    
        $scope.orderByMe = function(x) {
            $scope.myOrderBy = x;
        }    
    });
// script for modal popup 
function showMyModal(myTitle) {            
   $('#ywsModalTitle').html(myTitle);   
   $('#ywsModal').modal('show');
}
</script>

templates/ckeditor.html
<script src="https://cdn.ckeditor.com/4.9.2/standard/ckeditor.js"></script>

templates/datarange.html
<!-- script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

templates/datatable.html
<!-- datatable include start -->
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/dt-1.10.16/af-2.2.2/b-1.5.1/cr-1.4.1/fc-3.2.4/fh-3.1.3/kt-2.3.2/r-2.2.1/rg-1.0.2/rr-1.2.3/sc-1.4.4/sl-1.2.5/datatables.min.css"/>
<script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.16/af-2.2.2/b-1.5.1/cr-1.4.1/fc-3.2.4/fh-3.1.3/kt-2.3.2/r-2.2.1/rg-1.0.2/rr-1.2.3/sc-1.4.4/sl-1.2.5/datatables.min.js"></script>

<!-- print를 위한 javascript -->
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.flash.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/pdfmake.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.32/vfs_fonts.js"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.html5.min.js"></script>
<script type="text/javascript" language="javascript" src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.print.min.js"></script>
<!-- datatable include end --> 

templates/menu.html
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#" style="font-size:22px;text-decoration:none;color:#E02020" >
              <span >Meta</span>
              <font color=gray>-</font>
              <font color=#337ab7>eXpress</font>
          </a>
        </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li> <a href="{% url 'mdl2tbl:djbs01' %}"><span>모델비교</span></a></li>
          <!-- DB비교 메뉴 시작 -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><div>DB비교<span class="caret"></span></div></a>
              <ul class="dropdown-menu">                             
                <li> <a href="{% url 'mdl2tbl:djbs12' %}"><span>AURORA(dev<=>tst)비교</span></a></li>                           
                <li> <a href="{% url 'mdl2tbl:djbs13' %}"><span>AURORA인덱스(dev<=>tst)비교</span></a></li>  
                <li role="separator" class="divider"></li>
                <li><a href="{% url 'dq:tblCpy_list2' %}"><span>데이터 복제 조회</span></a></li>                                          
                <li><a href="{% url 'dq:tblCpy_list' %}"><span>데이터 복제 관리</span></a></li>                                          
              </ul>
            </li><!-- DB비교 종료 -->           
          <!-- 데이터수명주기 관련 메뉴 시작 -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">정보수명주기<span class="caret"></span></a>
              <ul class="dropdown-menu">                             
                <li> <a href="{% url 'mdl2tbl:djbs02' %}"><span>정보수명주기대상</span></a></li>
                <li> <a href="{% url 'dq:ilm_list' %}"><span>정보수명주기관리</span></a></li>
                <li role="separator" class="divider"></li>
                <li><a href="http://52.78.133.70/wiki/pages/viewpage.action?pageId=14065363"><span>정보수명주기 정리</span></a></li> 
              </ul>
            </li><!-- 데이터수명주기관련 메뉴 종료 -->                  
          <!-- DA# 관련 메뉴 시작 -->
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">데이터품질메터<span class="caret"></span></a>
            <ul class="dropdown-menu">                             
              <li> <a href={% url 'dq:vrfy_list' %}><span>검증메터관리</span></a></li>
              <li role="separator" class="divider"></li>
              <li> <a href={% url 'dq:vrfyLog_list' %}><span>검증수행결과</span></a></li>                           
            </ul>
          </li><!-- DA# 관련 메뉴 종료 -->      
          <!-- DA# 관련 메뉴 시작 -->
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">암호화대상<span class="caret"></span></a>
                <ul class="dropdown-menu">                             
                    <li> <a href={% url 'mdl2tbl:djbs03' %}><span>암호화대상목록</span></a></li>
                    <li> <a href={% url 'mdl2tbl:djbs04' %}><span>마스킹대상목록</span></a></li>
                    <li role="separator" class="divider"></li>
                    <li> <a href={% url 'mdl2tbl:djbs07' %}><span>직원명 컬럼</span></a></li>
                    <li> <a href={% url 'mdl2tbl:djbs08' %}><span>고객명 컬럼</span></a></li>
                    <li> <a href={% url 'mdl2tbl:djbs14' %}><span>개인정보 컬럼</span></a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="http://52.78.133.70/wiki/pages/viewpage.action?pageId=14057497"><span>개인정보 데이터 정의서</span></a></li>                                                
                  </ul>
          </li><!-- DA# 관련 메뉴 종료 -->                                                     
          <!-- DA# 관련 메뉴 시작 -->
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">데이터정의서<span class="caret"></span></a>
                <ul class="dropdown-menu">                             
                    <li> <a href={% url 'mdl2tbl:djbs05' %}><span>테이블정의서</span></a></li>
                    <li> <a href={% url 'mdl2tbl:djbs06' %}><span>컬럼정의서</span></a></li>                  
                    <li> <a href={% url 'mdl2tbl:djbs09' %}><span>코드정의서</span></a></li>
                    <li role="separator" class="divider"></li>                      
                    <li> <a href={% url 'mdl2tbl:djbs10' %}><span>속성사용테이블</span></a></li>
                    <li> <a href={% url 'mdl2tbl:djbs11' %}><span>컬럼사용테이블</span></a></li>
                  </ul>
          </li><!-- DA# 관련 메뉴 종료 -->
          <!-- 기타 관련 메뉴 시작 -->
          <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">etc.<span class="caret"></span></a>
                <ul class="dropdown-menu">                             
                    <li> <a href="{% url 'blog:pages' %}"><span>게시판</span></a></li>  
                    <li> <a href="{% url 'polls:index' %}"><span>투표</span></a></li>  
                  </ul>
          </li><!-- 기타 관련 메뉴 종료 -->                                                                 
        </ul>
        <!-- 오른쪽 버튼 -->
        <ul class="nav navbar-nav navbar-right">
          {% if user.is_active %}
          <li><a href="{% url 'login' %}"> <span class="glyphicon glyphicon-heart"></span> {{user.username}}</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li><a href="{% url 'login' %}"> <span class="glyphicon glyphicon-user"></span> Login</a></li>
          <li><a href="{% url 'admin:index' %}">Admin</a></li>
          {% endif %}     
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
    </nav>

templates/tinymce.html
<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<script>tinymce.init({ selector:'textarea' });</script>